services:

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
        - '5432:5432'
    volumes:
        - pg_data:/var/lib/postgresql/data

  ldap:
    image: osixia/openldap:1.5.0
    restart: always
    ports:
      - '389:389'
      - '636:636'
    environment:
      - LDAP_ORGANISATION=Dunder Mifflin Paper Company, Inc.
      - LDAP_DOMAIN=dunder-mifflin.com
      - LDAP_ADMIN_PASSWORD=bigboobz # https://www.youtube.com/watch?v=8GxqvnQyaxs
    volumes:
      - ldap_data:/var/lib/ldap


volumes:
  pg_data:
    driver: local
  ldap_data:
    driver: local